# Generated by Django 5.1.7 on 2025-04-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_price_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='UserName')),
                ('password', models.CharField(max_length=64, verbose_name='Password')),
            ],
        ),
    ]
