# Generated by Django 4.2.20 on 2025-04-19 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
