# Generated by Django 4.2.20 on 2025-04-19 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app01', '0004_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableNum', models.IntegerField(verbose_name='TableNum')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='OderDate')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TotalPrice')),
                ('server', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='UnitPrice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_item', to='app01.price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orderApp.order_new', verbose_name='OrderItem')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
